### ISSUE TITLE
it freezez

### ISSUE THREAD

**Issue by Vortex-Twisty** [HackerHansen/1v1.YEET-v2#4] opened 2021-03-05 17:03 UTC
chat engine frewezez and it doesnt ever atach pls help me

**Comment by HackerHansen** [comment] 2021-03-05 17:22
Duplicate of the issue at https://github.com/HackerHansen/1v1.YEET-v2/issues/3 so I'm closing this issue for now 

I couldn't reproduce this issue so I can't really find a way to fix it for now, sorry. Try using a different computer

**Closed by HackerHansen** 2021-03-05 17:22 UTC
