### ISSUE TITLE
Cheat-Engine freezes

### ISSUE THREAD

**Issue by YourActualMum** [HackerHansen/1v1.YEET-v2#3] opened 2021-03-03 19:40 UTC
If i wanna attach the process it just stop responding.
I have tried it manually a n d with firefox.
Still having the issue.

**Comment by HackerHansen** [comment] 2021-03-04 01:16
Do command prompt windows open briefly when you click attach?

**Comment by YourActualMum** [comment] 2021-03-04 06:25
Ye

**Comment by HackerHansen** [comment] 2021-03-04 07:39
How long does it freeze for? On some computers it might freeze for a few minutes while scanning.

**Comment by YourActualMum** [comment] 2021-03-04 07:58
It just freeze. I have to close it

**Comment by HackerHansen** [comment] 2021-03-04 15:56
How long do you wait before you close it?

**Comment by YourActualMum** [comment] 2021-03-04 16:02
The longest I waited for was like 20 mins

**Comment by HackerHansen** [comment] 2021-03-04 16:03
That's weird. Does the progress ever go up?

**Comment by YourActualMum** [comment] 2021-03-04 16:09
No it didn‘t. Also, if I try to attach manually it says I have entered a wrong PID, but I entered the right ohne. Lol

**Comment by HackerHansen** [comment] 2021-03-04 16:12
Are you sure 1v1.lol is the only tab open?

**Comment by YourActualMum** [comment] 2021-03-04 16:14
Yes. I tried so many things

**Comment by HackerHansen** [comment] 2021-03-04 16:16
That's really weird.

**Comment by HackerHansen** [comment] 2021-03-04 16:16
Normally I never do discord support, but add my alt IgotdemMONEY#9500 on discord (reply here with your username once you've added me, I'll delete these two comments so I don't get spammed by a bunch of people)

**Comment by Provincianoo** [comment] 2021-03-04 19:18
The exact same thing happened to me

**Comment by HackerHansen** [comment] 2021-03-05 16:44
I have been unable to reproduce this issue so idk how to fix it, sorry. I'll close this issue for now

**Closed by HackerHansen** 2021-03-05 16:44 UTC
