### ISSUE TITLE
aaa

### ISSUE THREAD

**Issue by brodyxawesome1** [HackerHansen/1v1.YEET-v2#11] opened 2021-04-07 03:42 UTC
how do make work on real fortnite likei t works but is there a way to not make it flickk to the ground

**Comment by HackerHansen** [comment] 2021-04-07 04:52
Grab a new color

**Comment by HackerHansen** [comment] 2021-04-07 04:53
Wait nvm I thought this issue was on another repo of mine, sorry. What do you mean by having it not flick at the ground?

**Comment by brodyxawesome1** [comment] 2021-04-08 01:14
when ever i aim it flicks to a diffrent poisetion

**Comment by HackerHansen** [comment] 2021-04-08 02:40
That's weird, there's no aimbot in this. I'm closing this for now since I can't reproduce and this issue shouldn't really be caused by 1v1.YEET

**Closed by HackerHansen** 2021-04-08 02:40 UTC
