### ISSUE TITLE
attempt to compare number with nil

### ISSUE THREAD

**Issue by banbuskox** [HackerHansen/1v1.YEET-v2#1] opened 2021-02-18 14:52 UTC
i got this error every time, tried on every browser, tried with auto attach on firefox and always getting this error
Error:[string "attachmentmode = 1
..."]:368: attempt to compare number with nil

**Comment by HackerHansen** [comment] 2021-02-18 15:47
Thank you for bringing this to my attention. I will work on a fix soon. This problem can be caused by having command prompt blocked. For now, try using manual mode.

**Comment by HackerHansen** [comment] 2021-02-18 15:47
Oops didn't mean to close this lmao

**Comment by banbuskox** [comment] 2021-02-18 17:24
> Thank you for bringing this to my attention. I will work on a fix soon. This problem can be caused by having command prompt blocked. For now, try using manual mode.

i said, error is on manual mode and auto mode

**Comment by HackerHansen** [comment] 2021-02-19 19:12
> > Thank you for bringing this to my attention. I will work on a fix soon. This problem can be caused by having command prompt blocked. For now, try using manual mode.
> 
> i said, error is on manual mode and auto mode

Command prompt also opens when you use manual mode to check the memory usage of the process

**Comment by HackerHansen** [comment] 2021-03-02 06:06
Ok, I pushed an update. I think I fixed it, but I never had any error so I wasn't able to test it, so I'm not sure how well the fix works. If you still have the same problem you can reopen this issue.

**Closed by HackerHansen** 2021-03-02 06:06 UTC

**Comment by banbuskox** [comment] 2021-03-05 18:47
Still have this issue, tried on 2 pc's

**Comment by HackerHansen** [comment] 2021-03-05 19:16
Do you get the same error?

**Comment by banbuskox** [comment] 2021-03-06 17:11
Yes

pt., 5 mar 2021, 20:17 użytkownik HackerHansen <notifications@github.com>
napisał:
